#!/usr/bin/env python3
"""Keep SEO tags, footers and sitemap.xml consistent across every page.

Run from anywhere:  python3 tools/seo_sync.py
Safe to re-run: it only adds tags a page is missing, replaces the footer
between the FOOTER markers, and rewrites sitemap.xml from PAGES below.
When you add a page, add it to PAGES and re-run.
"""
import html
import os
import re
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE = "https://nithin434.github.io"
OG_IMAGE = f"{SITE}/public/assets/img/avatar/og-image.jpg"
TODAY = date.today().isoformat()

# path, sitemap priority, changefreq, breadcrumb name.
# Images and videos for the sitemap are read from each page's <img> and <video> tags.
PAGES = [
    ("index.html", "1.0", "monthly", "Home"),
    ("public/projects.html", "0.9", "monthly", "Projects"),
    ("public/cv.html", "0.9", "monthly", "CV"),
    ("public/gallery.html", "0.8", "monthly", "Gallery"),
    ("public/topics.html", "0.7", "monthly", "Topics"),
    ("public/cite.html", "0.6", "yearly", "Cite"),
]
# One page per project, generated by tools/make_project_pages.py.
PAGES += [(f"public/projects/{f.name}", "0.8", "monthly", None)
          for f in sorted((ROOT / "public/projects").glob("*.html"))]
PDFS = [("public/CV.pdf", "0.8", "monthly")]

# Profiles and publications linked from every footer (backlinks).
PROFILES = [
    ("https://github.com/nithin434", "GitHub"),
    ("https://linkedin.com/in/nithin-jambula", "LinkedIn"),
    ("https://doi.org/10.1109/AIRC69745.2026.11631384", "IEEE AIRC 2026"),
    ("https://doi.org/10.1109/ISAI-NLP66160.2025.11320726", "IEEE iSAI-NLP 2025"),
    ("https://pypi.org/project/apk2abb/", "PyPI"),
    ("https://air.vitap.ac.in/", "AIR Centre, VIT-AP"),
    ("https://vitap.ac.in/", "VIT-AP University"),
]
SITE_LINKS = [
    ("index.html", "home"), ("public/projects.html", "projects"), ("public/gallery.html", "gallery"),
    ("public/cv.html", "cv"), ("public/topics.html", "topics"), ("public/cite.html", "cite"),
    ("public/CV.pdf", "cv.pdf"), ("public/atom.xml", "atom"), ("public/rss.xml", "rss"),
    ("public/feed.json", "json feed"), ("sitemap.xml", "sitemap"), ("llms.txt", "llms.txt"),
]
FOOTER_START, FOOTER_END = "<!-- FOOTER:start -->", "<!-- FOOTER:end -->"


def rel(from_page, target):
    """Relative link from one page to a repo-root path (works at any folder depth)."""
    here = os.path.dirname(from_page) or "."
    if target == "index.html":
        up = os.path.relpath(".", here)
        return "./" if up == "." else up + "/"
    return os.path.relpath(target, here)


def page_url(path):
    return f"{SITE}/" if path == "index.html" else f"{SITE}/{path}"


def footer(page):
    profiles = " ·\n  ".join(f'<a href="{u}" rel="me noopener">{t}</a>' if "nithin" in u else f'<a href="{u}">{t}</a>'
                              for u, t in PROFILES)
    links = " · ".join(f'<a href="{rel(page, p)}">{t}</a>' for p, t in SITE_LINKS)
    return (f'{FOOTER_START}\n<div id="footer">\n  {profiles}<br>\n  {links}<br>\n'
            f'  © 2023–{date.today().year} Nithin Jambula · '
            f'<a href="mailto:nithinjambula89@gmail.com">nithinjambula89@gmail.com</a> · '
            f'text under <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>\n</div>\n{FOOTER_END}')


def meta(s, pattern):
    m = re.search(pattern, s)
    return html.unescape(m.group(1)) if m else ""


def sync_page(path, crumb):
    p = ROOT / path
    s = p.read_text()
    title = meta(s, r"<title>(.*?)</title>")
    desc = meta(s, r'<meta name="description" content="([^"]*)"')
    url = page_url(path)
    here = os.path.dirname(path) or "."
    icon_prefix = "" if here == "." else os.path.relpath(".", here) + "/"
    asset = os.path.relpath("public", here) + "/"
    asset = "" if asset == "./" else asset
    esc = lambda t: html.escape(t, quote=True)

    wanted = [
        ("name=\"robots\"", '<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1">'),
        ("theme-color", '<meta name="theme-color" content="#000000">'),
        ("og:type", f'<meta property="og:type" content="{"profile" if path in ("index.html", "public/cv.html") else "website"}">'),
        ("og:site_name", '<meta property="og:site_name" content="Nithin Jambula">'),
        ("og:title", f'<meta property="og:title" content="{esc(title)}">'),
        ("og:description", f'<meta property="og:description" content="{esc(desc)}">'),
        ("og:url", f'<meta property="og:url" content="{url}">'),
        ("og:image\"", f'<meta property="og:image" content="{OG_IMAGE}">'),
        ("og:locale", '<meta property="og:locale" content="en_US">'),
        ("twitter:card", '<meta name="twitter:card" content="summary_large_image">'),
        ("twitter:title", f'<meta name="twitter:title" content="{esc(title)}">'),
        ("twitter:description", f'<meta name="twitter:description" content="{esc(desc)}">'),
        ("twitter:image", f'<meta name="twitter:image" content="{OG_IMAGE}">'),
        ("apple-touch-icon", f'<link rel="apple-touch-icon" href="{asset}assets/img/avatar/avatar-180.png">'),
        ("rel=\"manifest\"", f'<link rel="manifest" href="{asset}manifest.json">'),
        ("application/atom+xml", f'<link rel="alternate" type="application/atom+xml" title="Nithin Jambula (Atom)" href="{asset}atom.xml">'),
        ("application/rss+xml", f'<link rel="alternate" type="application/rss+xml" title="Nithin Jambula (RSS)" href="{asset}rss.xml">'),
        ("rel=\"sitemap\"", f'<link rel="sitemap" type="application/xml" title="Sitemap" href="{icon_prefix}sitemap.xml">'),
        ("rel=\"author\"", f'<link rel="author" href="{asset}humans.txt">'),
        ('rel="me" href="https://github.com', '<link rel="me" href="https://github.com/nithin434">'),
        ('rel="me" href="https://linkedin.com', '<link rel="me" href="https://linkedin.com/in/nithin-jambula">'),
    ]
    missing = [tag for key, tag in wanted if key not in s]
    if crumb and crumb != "Home" and "BreadcrumbList" not in s:
        missing.append(
            '<script type="application/ld+json">\n'
            '{"@context": "https://schema.org", "@type": "BreadcrumbList", "itemListElement": [\n'
            f'  {{"@type": "ListItem", "position": 1, "name": "Home", "item": "{SITE}/"}},\n'
            f'  {{"@type": "ListItem", "position": 2, "name": "{crumb}", "item": "{url}"}}\n]}}\n</script>')
    if missing:
        anchor = s.index('<link rel="stylesheet"')
        s = s[:anchor] + "\n".join(missing) + "\n" + s[anchor:]

    # Replace the footer (first run: the old <div id="footer">...</div>).
    new_footer = footer(path)
    if FOOTER_START in s:
        s = re.sub(re.escape(FOOTER_START) + r".*?" + re.escape(FOOTER_END), lambda _: new_footer, s, flags=re.S)
    else:
        s = re.sub(r'<div id="footer">.*?</div>', lambda _: new_footer, s, count=1, flags=re.S)
    p.write_text(s)
    return len(missing)


def abs_url(page, src):
    """Absolute URL for a src/href found on a page."""
    if src.startswith("http"):
        return src
    base = Path(page).parent
    return f"{SITE}/{(base / src).as_posix()}".replace("/./", "/")


def media_on(page):
    """(images, videos) shown on a page, from its <img> and <video> tags."""
    s = (ROOT / page).read_text()
    images, seen = [], set()
    for tag in re.findall(r"<img\b[^>]*>", s):
        src = re.search(r'\ssrc="([^"]+)"', tag)
        alt = re.search(r'\salt="([^"]*)"', tag)
        if not src or not (alt and alt.group(1)):
            continue  # decorative images have empty alt
        url = abs_url(page, src.group(1))
        if url not in seen:
            seen.add(url)
            images.append((url, html.unescape(alt.group(1))))
    videos = []
    for fig in re.findall(r"<figure[^>]*>\s*<video\b.*?</figure>", s, flags=re.S):
        src = re.search(r'<source src="([^"]+)"', fig)
        poster = re.search(r'poster="([^"]+)"', fig)
        cap = re.search(r"<figcaption>(.*?)</figcaption>", fig, flags=re.S)
        text = html.unescape(re.sub(r"<[^>]+>", "", cap.group(1))).strip() if cap else "Video"
        title = text.split(".")[0].strip()
        if src and poster:
            videos.append((abs_url(page, src.group(1)), abs_url(page, poster.group(1)), title, text))
    return images, videos


def write_sitemap():
    esc = lambda t: html.escape(t, quote=False)
    out = ['<?xml version="1.0" encoding="UTF-8"?>',
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
           '        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"',
           '        xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">']
    n_img = n_vid = 0
    for path, prio, freq, _ in PAGES:
        images, videos = media_on(path)
        out += ["  <url>", f"    <loc>{page_url(path)}</loc>", f"    <lastmod>{TODAY}</lastmod>",
                f"    <changefreq>{freq}</changefreq>", f"    <priority>{prio}</priority>"]
        for url, cap in images:
            out.append(f"    <image:image><image:loc>{url}</image:loc><image:title>{esc(cap)}</image:title></image:image>")
        for url, poster, title, text in videos:
            out += ["    <video:video>", f"      <video:thumbnail_loc>{poster}</video:thumbnail_loc>",
                    f"      <video:title>{esc(title)}</video:title>", f"      <video:description>{esc(text)}</video:description>",
                    f"      <video:content_loc>{url}</video:content_loc>", "      <video:family_friendly>yes</video:family_friendly>",
                    "    </video:video>"]
        n_img += len(images); n_vid += len(videos)
        out.append("  </url>")
    for path, prio, freq in PDFS:
        out += ["  <url>", f"    <loc>{SITE}/{path}</loc>", f"    <lastmod>{TODAY}</lastmod>",
                f"    <changefreq>{freq}</changefreq>", f"    <priority>{prio}</priority>", "  </url>"]
    out.append("</urlset>\n")
    (ROOT / "sitemap.xml").write_text("\n".join(out))
    return n_img, n_vid


if __name__ == "__main__":
    for path, _, _, crumb in PAGES:
        print(f"{path}: added {sync_page(path, crumb)} tags, footer synced")
    n_img, n_vid = write_sitemap()
    print(f"sitemap.xml written: {len(PAGES) + len(PDFS)} URLs, {n_img} images, {n_vid} videos")
